version: '3'
services:
  mysql:
    image: mysql
    container_name: "mysql-thibaut"
    environment:
      - MYSQL_ROOT_PASSWORD=sonarqube
      - MYSQL_DATABASE=sonarqube
      - MYSQL_USER=sonarqube
      - MYSQL_PASSWORD=sonarqube
  sonarqube:
    image: sonarqube:6.7
    container_name: "sonarqube-thibaut"
    hostname: "sonarqube-thibaut"
    links:
      - mysql
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
